site_name: "Zabbix Template: EL9 Stack"
repo_url: https://github.com/radiorabe/rabe-zabbix
repo_name: radiorabe/rabe-zabbix
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav
nav:
  - README: index.md
