---
# hack/plays/manage.yml
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: rabe-zabbix
  title: RaBe Zabbix
  description: |
    Zabbix is the main monitoring system at RaBe.
  annotations:
    github.com/project-slug: radiorabe/rabe-zabbix
  links:
    - url: https://monitoring.service.int.rabe.ch
      title: Zabbix Web
spec:
  owner: it-reaktion
---
# hack/plays/manage.yml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rabe-zabbix-templates
  title: RaBe Zabbix Templates
  description: |
    Zabbix templates available for use in our Zabbix instance.
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: radiorabe/rabe-zabbix
spec:
  type: library
  lifecycle: experimental
  owner: it-reaktion
  partOf:
    - system:default/rabe-zabbix
---
# Overrides/Apache_by_HTTP/6.4/Apache_by_HTTP.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zabbix-template-Apache_by_HTTP
  title: "Zabbix Template: Apache by HTTP"
  description: |
    Get metrics from mod_status module using HTTP agent.
    https://httpd.apache.org/docs/current/mod/mod_status.html

    You can discuss this template or leave feedback on our forum https://www.zabbix.com/forum/zabbix-suggestions-and-feedback/384764-discussion-thread-for-official-zabbix-template-apache

    Generated by official Zabbix template tool "Templator"

    ## Changes

    These changes are part of [RaBe's Zabbix template and helpers
    collection](https://github.com/radiorabe/rabe-zabbix).

    * Added `{$APACHE.STATUS.HOST}` instead of `{HOST.NAME}` for agentless use

  annotations:
    github.com/project-slug: radiorabe/rabe-zabbix
spec:
  type: zabbix-template
  lifecycle: experimental
  owner: it-reaktion
  partOf:
    - component:default/rabe-zabbix-templates
---
# Stacks/Operating_systems/EL7_Stack/6.4/EL7_Stack.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zabbix-template-EL7_Stack
  title: "Zabbix Template: EL7 Stack"
  description: |
    Base stack template for CentOS 7 based systems.

    This template is part of [RaBe's Zabbix template and helpers
    collection](https://github.com/radiorabe/rabe-zabbix).

  annotations:
    github.com/project-slug: radiorabe/rabe-zabbix
spec:
  type: zabbix-template
  lifecycle: experimental
  owner: it-reaktion
  partOf:
    - component:default/rabe-zabbix-templates
---
# Stacks/Operating_systems/EL8_Stack/6.4/EL8_Stack.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zabbix-template-EL8_Stack
  title: "Zabbix Template: EL8 Stack"
  description: |
    Base stack template for CentOS 8 Stream based systems.

    This template is part of [RaBe's Zabbix template and helpers
    collection](https://github.com/radiorabe/rabe-zabbix).

  annotations:
    github.com/project-slug: radiorabe/rabe-zabbix
spec:
  type: zabbix-template
  lifecycle: experimental
  owner: it-reaktion
  partOf:
    - component:default/rabe-zabbix-templates
---
# Stacks/Operating_systems/EL9_Stack/6.4/EL9_Stack.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zabbix-template-EL9_Stack
  title: "Zabbix Template: EL9 Stack"
  description: |
    Base stack template for AlmaLinux 9 based systems.

    This template is part of [RaBe's Zabbix template and helpers
    collection](https://github.com/radiorabe/rabe-zabbix).

  annotations:
    github.com/project-slug: radiorabe/rabe-zabbix
spec:
  type: zabbix-template
  lifecycle: experimental
  owner: it-reaktion
  partOf:
    - component:default/rabe-zabbix-templates
---
# Stacks/Applications/systemd_Stack/6.4/systemd_Stack.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zabbix-template-systemd_Stack
  title: "Zabbix Template: systemd Stack"
  description: |
    The [systemd](https://systemd.io) combines all the pieces of
    systemd that ususally run on a system host.

    This template is part of [RaBe's Zabbix template and helpers
    collection](https://github.com/radiorabe/rabe-zabbix).

  annotations:
    github.com/project-slug: radiorabe/rabe-zabbix
spec:
  type: zabbix-template
  lifecycle: experimental
  owner: it-reaktion
  partOf:
    - component:default/rabe-zabbix-templates
---
# Stacks/Servers/EL9_KVM_VM_Stack/6.4/EL9_KVM_VM_Stack.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zabbix-template-EL9_KVM_VM_Stack
  title: "Zabbix Template: EL9 KVM VM Stack"
  description: |
    Base stack template for EL9 based virtual machines.

    This template is part of [RaBe's Zabbix template and helpers
    collection](https://github.com/radiorabe/rabe-zabbix).

  annotations:
    github.com/project-slug: radiorabe/rabe-zabbix
spec:
  type: zabbix-template
  lifecycle: experimental
  owner: it-reaktion
  partOf:
    - component:default/rabe-zabbix-templates
---
# Stacks/Servers/EL7_KVM_VM_Stack/6.4/EL7_KVM_VM_Stack.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zabbix-template-EL7_KVM_VM_Stack
  title: "Zabbix Template: EL7 KVM VM Stack"
  description: |
    Base stack template for EL7 based virtual machines.

    This template is part of [RaBe's Zabbix template and helpers
    collection](https://github.com/radiorabe/rabe-zabbix).

  annotations:
    github.com/project-slug: radiorabe/rabe-zabbix
spec:
  type: zabbix-template
  lifecycle: experimental
  owner: it-reaktion
  partOf:
    - component:default/rabe-zabbix-templates
---
# Stacks/Servers/EL8_KVM_VM_Stack/6.4/EL8_KVM_VM_Stack.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zabbix-template-EL8_KVM_VM_Stack
  title: "Zabbix Template: EL8 KVM VM Stack"
  description: |
    Base stack template for EL8 based virtual machines.

    This template is part of [RaBe's Zabbix template and helpers
    collection](https://github.com/radiorabe/rabe-zabbix).

  annotations:
    github.com/project-slug: radiorabe/rabe-zabbix
spec:
  type: zabbix-template
  lifecycle: experimental
  owner: it-reaktion
  partOf:
    - component:default/rabe-zabbix-templates
---
# Templates/Applications/auditd/6.4/auditd.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zabbix-template-auditd
  title: "Zabbix Template: auditd"
  description: |
    Keeps track of [auditd](https://people.redhat.com/sgrubb/audit/).

    This template is part of [RaBe's Zabbix template and helpers
    collection](https://github.com/radiorabe/rabe-zabbix).

  annotations:
    github.com/project-slug: radiorabe/rabe-zabbix
spec:
  type: zabbix-template
  lifecycle: experimental
  owner: it-reaktion
  partOf:
    - component:default/rabe-zabbix-templates
---
# Templates/Applications/chrony/6.4/chrony.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zabbix-template-chrony
  title: "Zabbix Template: chrony"
  description: |
    Keeps track of [chrony](https://chrony-project.org/).

    Needs the following configuration:
    ```
    AllowKey=system.run[/usr/bin/chronyc -c activity]
    AllowKey=system.run[/usr/bin/chronyc -c tracking]
    ```

    This template is part of [RaBe's Zabbix template and helpers
    collection](https://github.com/radiorabe/rabe-zabbix).

  annotations:
    github.com/project-slug: radiorabe/rabe-zabbix
spec:
  type: zabbix-template
  lifecycle: experimental
  owner: it-reaktion
  partOf:
    - component:default/rabe-zabbix-templates
---
# Templates/Applications/Cronie/6.4/Cronie.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zabbix-template-Cronie
  title: "Zabbix Template: Cronie"
  description: |
    Monitoring of [Cronie](https://github.com/cronie-crond/cronie).

    This template is part of [RaBe's Zabbix template and helpers
    collection](https://github.com/radiorabe/rabe-zabbix).

  annotations:
    github.com/project-slug: radiorabe/rabe-zabbix
spec:
  type: zabbix-template
  lifecycle: experimental
  owner: it-reaktion
  partOf:
    - component:default/rabe-zabbix-templates
---
# Templates/Applications/timedatectl/6.4/timedatectl.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zabbix-template-timedatectl
  title: "Zabbix Template: timedatectl"
  description: |
    Keeps track of the time and date subsystem by running timedatectl status.

    Needs the following configuration:
    ```
    AllowKey=system.run[/usr/bin/timedatectl show]
    ```

    See [here](https://www.freedesktop.org/software/systemd/man/latest/timedatectl.html)
    for more information about timedatectl.

    This template is part of [RaBe's Zabbix template and helpers
    collection](https://github.com/radiorabe/rabe-zabbix).

  annotations:
    github.com/project-slug: radiorabe/rabe-zabbix
spec:
  type: zabbix-template
  lifecycle: experimental
  owner: it-reaktion
  partOf:
    - component:default/rabe-zabbix-templates
---
# Templates/Applications/Zabbix_unsupported_items/6.4/Zabbix_unsupported_items.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zabbix-template-Zabbix_unsupported_items
  title: "Zabbix Template: Zabbix unsupported items"
  description: |
    Implementation agnostic monitoring of unsupported items from Zabbix internal.

    Used as a mix-in to most low-level stack templates.

    This template is part of [RaBe's Zabbix template and helpers
    collection](https://github.com/radiorabe/rabe-zabbix).

  annotations:
    github.com/project-slug: radiorabe/rabe-zabbix
spec:
  type: zabbix-template
  lifecycle: experimental
  owner: it-reaktion
  partOf:
    - component:default/rabe-zabbix-templates
---
# Templates/Applications/firewalld/6.4/firewalld.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zabbix-template-firewalld
  title: "Zabbix Template: firewalld"
  description: |
    Keeps track of [firewalld](https://firewalld.org/).

    This template is part of [RaBe's Zabbix template and helpers
    collection](https://github.com/radiorabe/rabe-zabbix)

  annotations:
    github.com/project-slug: radiorabe/rabe-zabbix
spec:
  type: zabbix-template
  lifecycle: experimental
  owner: it-reaktion
  partOf:
    - component:default/rabe-zabbix-templates
---
# Templates/Applications/tuned/6.4/tuned.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zabbix-template-tuned
  title: "Zabbix Template: tuned"
  description: |
    Monitoring of [tuned](https://tuned-project.org/).

    This template is part of [RaBe's Zabbix template and helpers
    collection](https://github.com/radiorabe/rabe-zabbix).

  annotations:
    github.com/project-slug: radiorabe/rabe-zabbix
spec:
  type: zabbix-template
  lifecycle: experimental
  owner: it-reaktion
  partOf:
    - component:default/rabe-zabbix-templates
---
# Templates/Applications/rsyslog/6.4/rsyslog.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zabbix-template-rsyslog
  title: "Zabbix Template: rsyslog"
  description: |
    Monitoring of [rsyslog](https://www.rsyslog.com/).

    This template is part of [RaBe's Zabbix template and helpers
    collection](https://github.com/radiorabe/rabe-zabbix).

  annotations:
    github.com/project-slug: radiorabe/rabe-zabbix
spec:
  type: zabbix-template
  lifecycle: experimental
  owner: it-reaktion
  partOf:
    - component:default/rabe-zabbix-templates
---
# Templates/Applications/sssd/6.4/sssd.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zabbix-template-sssd
  title: "Zabbix Template: sssd"
  description: |
    Monitoring of [sssd](https://sssd.io).

    This template is part of [RaBe's Zabbix template and helpers
    collection](https://github.com/radiorabe/rabe-zabbix).

  annotations:
    github.com/project-slug: radiorabe/rabe-zabbix
spec:
  type: zabbix-template
  lifecycle: experimental
  owner: it-reaktion
  partOf:
    - component:default/rabe-zabbix-templates
---
# Templates/Applications/gssproxy/6.4/gssproxy.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zabbix-template-gssproxy
  title: "Zabbix Template: gssproxy"
  description: |
    Monitoring of [gssproxy](https://pagure.io/gssproxy).

    This template is part of [RaBe's Zabbix template and helpers
    collection](https://github.com/radiorabe/rabe-zabbix).

  annotations:
    github.com/project-slug: radiorabe/rabe-zabbix
spec:
  type: zabbix-template
  lifecycle: experimental
  owner: it-reaktion
  partOf:
    - component:default/rabe-zabbix-templates
---
# Templates/Applications/rpc.gssd/6.4/rpc.gssd.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zabbix-template-rpc.gssd
  title: "Zabbix Template: rpc.gssd"
  description: |
    Monitoring of [rpc.gssd](https://linux.die.net/man/8/rpc.gssd).

    This template is part of [RaBe's Zabbix template and helpers
    collection](https://github.com/radiorabe/rabe-zabbix).

  annotations:
    github.com/project-slug: radiorabe/rabe-zabbix
spec:
  type: zabbix-template
  lifecycle: experimental
  owner: it-reaktion
  partOf:
    - component:default/rabe-zabbix-templates
---
# Templates/Applications/systemd-logind/6.4/systemd-logind.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zabbix-template-systemd-logind
  title: "Zabbix Template: systemd-logind"
  description: |
    Monitoring of [systemd-logind](https://www.freedesktop.org/software/systemd/man/latest/systemd-logind.service.html).

    This template is part of [RaBe's Zabbix template and helpers
    collection](https://github.com/radiorabe/rabe-zabbix).

  annotations:
    github.com/project-slug: radiorabe/rabe-zabbix
spec:
  type: zabbix-template
  lifecycle: experimental
  owner: it-reaktion
  partOf:
    - component:default/rabe-zabbix-templates
---
# Templates/Applications/systemd-journald/6.4/systemd-journald.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zabbix-template-systemd-journald
  title: "Zabbix Template: systemd-journald"
  description: |
    Monitoring of [systemd-journald](https://www.freedesktop.org/software/systemd/man/latest/systemd-journald.service.html).

    This template is part of [RaBe's Zabbix template and helpers
    collection](https://github.com/radiorabe/rabe-zabbix).

  annotations:
    github.com/project-slug: radiorabe/rabe-zabbix
spec:
  type: zabbix-template
  lifecycle: experimental
  owner: it-reaktion
  partOf:
    - component:default/rabe-zabbix-templates
---
# Templates/Applications/systemd-udevd/6.4/systemd-udevd.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zabbix-template-systemd-udevd
  title: "Zabbix Template: systemd-udevd"
  description: |
    Monitoring of [systemd-udevd](https://www.freedesktop.org/software/systemd/man/latest/systemd-udevd.service.html).

    This template is part of [RaBe's Zabbix template and helpers
    collection](https://github.com/radiorabe/rabe-zabbix).

  annotations:
    github.com/project-slug: radiorabe/rabe-zabbix
spec:
  type: zabbix-template
  lifecycle: experimental
  owner: it-reaktion
  partOf:
    - component:default/rabe-zabbix-templates
---
# Templates/Applications/certmonger/6.4/certmonger.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zabbix-template-certmonger
  title: "Zabbix Template: certmonger"
  description: |
    Monitoring of [certmonger](https://www.freeipa.org/page/Certmonger).

    This template is part of [RaBe's Zabbix template and helpers
    collection](https://github.com/radiorabe/rabe-zabbix).

  annotations:
    github.com/project-slug: radiorabe/rabe-zabbix
spec:
  type: zabbix-template
  lifecycle: experimental
  owner: it-reaktion
  partOf:
    - component:default/rabe-zabbix-templates
---
# Templates/Applications/qemu-ga/6.4/qemu-ga.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zabbix-template-qemu-ga
  title: "Zabbix Template: QEMU Guest Agent"
  description: |
    Monitoring of the [QEMU Guest Agent](https://www.qemu.org/docs/master/interop/qemu-ga.html).

    This template is part of [RaBe's Zabbix template and helpers
    collection](https://github.com/radiorabe/rabe-zabbix).

  annotations:
    github.com/project-slug: radiorabe/rabe-zabbix
spec:
  type: zabbix-template
  lifecycle: experimental
  owner: it-reaktion
  partOf:
    - component:default/rabe-zabbix-templates
