site_name: RaBe Zabbix
repo_url: https://github.com/radiorabe/rabe-zabbix
repo_name: radiorabe/rabe-zabbix

theme:
  name: "material"
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: '#00c9bf'
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: '#00c9bf'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - content.code.copy

markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences

extra:
  social:
    - icon: material/web
      link: https://rabe.ch

extra_css:
- css/style.css

plugins:
- search
- gen-files:
    scripts:
    - docs/gen_ref_pages.py
- literate-nav

nav:
  - README: index.md
  - Stacks: Stacks/
  - Templates: Templates/
  - Overrides: Overrides/

watch:
  - README.md
  - Stacks/
  - Templates/
  - Overrides/
