---
- name: Manage RaBe Templates
  hosts: [localhost]

  vars:
    rabe_zabbix_templates:
      - search: "auditd"
      - search: "certmonger"
      - search: "chrony"
      - search: "Cronie"
      - search: "EL7 KVM VM Stack"
      - search: "EL7 Stack"
      - search: "EL8 KVM VM Stack"
      - search: "EL8 Stack"
      - search: "EL9 KVM VM Stack"
      - search: "EL9 Stack"
      - search: "firewalld"
      - search: "gssproxy"
      - search: "qemu-ga"
      - search: "rsyslog"
      - search: "rpc.gssd"
      - search: "sssd"
      - search: "systemd-journald"
      - search: "systemd-logind"
      - search: "systemd-udevd"
      - search: "systemd Stack"
      - search: "timedatectl"
      - search: "tuned"
      - search: "Zabbix unsupported items"
    ansible_host: 'vm-0040.service.int.rabe.ch'
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: true
    ansible_zabbix_url_path: ''

  tasks:
    - name: 'RaBe Zabbix : Set API Key'
      ansible.builtin.set_fact:
        ansible_zabbix_auth_key: '{{ zabbix_auth_key | mandatory }}'

    - name: Get RaBe template as YAML
      community.zabbix.zabbix_template_info:
        template_name: '{{ item.search }}'
        format: yaml
        omit_date: no
      with_items: '{{ rabe_zabbix_templates }}'
      register: info

    - ansible.builtin.file:
        state: directory
        path: '{{ (item.template_yaml | from_yaml).zabbix_export.template_groups[0].name | replace(" ", "_") }}/{{ item.item.search | replace(" ", "_") }}/{{ (item.template_yaml | from_yaml).zabbix_export.version }}'
      with_items: '{{ info.results }}'

    - ansible.builtin.copy:
        dest: '{{ (item.template_yaml | from_yaml).zabbix_export.template_groups[0].name | replace(" ", "_") }}/{{ item.item.search | replace(" ", "_") }}/{{ (item.template_yaml | from_yaml).zabbix_export.version }}/{{ item.item.search | replace(" ", "_") }}.yaml'
        content: '{{ item.template_yaml }}'
      with_items: '{{ info.results }}'
