
---
- name: Update README
  hosts: [localhost]
  gather_facts: yes

  tasks:
    - ansible.builtin.find:
        path: "../../Stacks"
        file_type: "directory"
        depth: 3
        recurse: yes
      register: stacks

    - ansible.builtin.find:
        path: "../../Templates"
        file_type: "directory"
        depth: 3
        recurse: yes
      register: templates

    - ansible.builtin.find:
        path: "../../Overrides"
        file_type: "directory"
        depth: 2
        recurse: yes
      register: overrides

    - name: "Generate top-level README.md"
      ansible.builtin.copy:
        dest: '../../README.md'
        content: |
          # rabe-zabbix

          Collection of various [Zabbix](http://www.zabbix.com/) templates and
          helper scripts created or used by [Radio Bern RaBe](http://rabe.ch/).

          See below for an overview of our templates. We group our templates
          similar to how Zabbix-out-of-the-box templates are grouped.

          ## Stacks

          Every host within Zabbix gets a specific stack template assigned according
          to its role. The stack exactly defines the setup of this host and will be
          re-used if there is more than one host with the same role.

          As an example, a host which servers a MediaWiki instance, will get the
          stack template <code>MediaWiki Stack</code> assigned. The stack template
          might include the operating system template <code>EL9 Stack</code>, the
          application templates <code>Apache by HTTP</code>, <code>PHP-FPM by HTTP</code>
          and <code>MariaDB by agent 2</code>.

          This ensures great modularity, reusability and avoids unecessary
          inheritance problems.

          {% set flat_stacks = (stacks.files | sort(attribute='path') | map(attribute='path')) %}
          {% for stack in flat_stacks %}
          {% if (stack.split('/') | length) == 4 %}

          ### {{ stack.split('/')[2:4] | join(": ") | replace("_", " ") }}
          
          | Name | 3.0 | 6.4 | 7.0 |
          | ---- | --- | --- | --- |
          {% endif %}
          {% if (stack.split('/') | length) == 5 %}
          | {{ stack.split('/')[4].replace("_", " ") }} | {% if stack + '/3.0' in flat_stacks %}[✅](./{{ stack.split('/')[2:] | join('/') }}/3.0){% endif %} | {% if stack + '/6.4' in flat_stacks %}[✅](./{{ stack.split('/')[2:] | join('/') }}/6.4){% endif %} | {% if stack + '/7.0' in flat_stacks %}[✅](./{{ stack.split('/')[2:] | join('/') }}/7.0){% endif %} |
          {% endif %}
          {% endfor %}

          ## Templates
          {% set flat_templates = (templates.files | sort(attribute='path') | map(attribute='path')) %}
          {% for template in flat_templates %}
          {% if (template.split('/') | length) == 4 %}

          ### {{ template.split('/')[2:4] | join(": ") | replace("_", " ") }}
          
          | Name | 3.0 | 6.4 | 7.0 |
          | ---- | --- | --- | --- |
          {% endif %}
          {% if (template.split('/') | length) == 5 %}
          | {{ template.split('/')[4].replace("_", " ") }} | {% if template + '/3.0' in flat_templates %}[✅](./{{ template.split('/')[2:] | join('/') }}/3.0){% endif %} | {% if template + '/6.4' in flat_templates %}[✅](./{{ template.split('/')[2:] | join('/') }}/6.4){% endif %} | {% if template + '/7.0' in flat_templates %}[✅](./{{ template.split('/')[2:] | join('/') }}/7.0){% endif %} |
          {% endif %}
          {% endfor %}

          ## Overrides
          {% set flat_overrides = (overrides.files | sort(attribute='path') | map(attribute='path')) %}

          In some cases we override the Zabbix out-of-the-box templates to
          ensure they fit our use case. We publish the changed templates along
          with a generated diff against its upstream version.

          | Name | 6.4 | 7.0 |
          | ---- | --- | --- |
          {% for override in flat_overrides %}
          {% if (override.split('/') | length) == 4 %}
          | {{ override.split('/')[3] | replace("_", " ") }} | {% if override + '/6.4' in flat_overrides %}[✅](./{{ override.split('/')[2:] | join('/') }}/6.4){% endif %} | {% if override + '/7.0' in flat_overrides %}[✅](./{{ override.split('/')[2:] | join('/') }}/7.0){% endif %} |
          {% endif %}
          {% endfor %}

          ## Zabbix Version Support

          We primarily support versions of Zabbix we use in production.

          | Version | Supported | Description |
          | ------- | --------- | ----------- |
          | 3.0 | ✅ | legacy RaBe environment |
          | 6.4 | ✅ | for LTS preparation work until 7.0 is available |
          | 7.0 | ✅ | once released |

          ## Contributing
          
          See [CONTRIBUTING.md](./CONTRIBUTING.md) for our contributor documentation.

          ## License
          
          This template collection is free software: you can redistribute it and/or modify it under
          the terms of the GNU Affero General Public License as published by the Free
          Software Foundation, version 3 of the License.

          ## Copyright
          
          Copyright (c) 2017 - {{ ansible_date_time.year }} [Radio Bern RaBe](http://www.rabe.ch)

    - ansible.builtin.find:
        paths: 
          - "../../Overrides"
          - "../../Stacks"
          - "../../Templates"
        patterns:
          - "*.yaml"
        file_type: "file"
        depth: 5
        recurse: yes
      register: yaml

    - name: "Generate template README.md"
      ansible.builtin.copy:
        dest: '{{ item | dirname }}/README.md'
        content: |
          {% set triggers = [] %}
          {% set tpl = (lookup('ansible.builtin.file', item) | from_yaml).zabbix_export.templates[0] %}
          # Zabbix Template: {{ tpl.name }}

          {% for tag in tpl.tags %}![{{ tag.tag }}: {{ tag.value }}](https://img.shields.io/badge/{{ tag.tag }}-{{ tag.value }}-00c9bf){% endfor %}{% if 'vendor' in tpl %}![vendor: {{ tpl.vendor.name }}](https://img.shields.io/badge/vendor-{{ tpl.vendor.name }}-00c9bf)![version: {{ tpl.vendor.version }}](https://img.shields.io/badge/version-{{ tpl.vendor.version | replace("-", "--") }}-00c9bf){% endif %}


          {{ tpl.description }}
          {% if 'templates' in tpl %}

          ## Linked Templates

          This Zabbix template depends on the following templates.

          {% for dep in tpl.templates %}
          * {{ dep.name }}
          {% endfor %}
          {% endif %}
          {% if 'macros' in tpl %}

          ## Macros

          The following Zabbix macros are configured via this template.
          {% for macro in tpl.macros %}

          ### Macro: `{{ macro.macro }}`

          {{ macro.description if 'description' in macro }}

          Default:
          ```
          {{ macro.value if 'value' in macro }}
          ```
          {% endfor %}
          {% endif %}
          {% if 'items' in tpl %}

          ## Items
          {% for item in tpl['items'] %}

          ### Item: {{ item.name }}

          {% for tag in item.tags %}![{{ tag.tag }}: {{ tag.value }}](https://img.shields.io/badge/{{ tag.tag }}-{{ tag.value }}-00c9bf){% endfor %}
          {{ triggers.append(item.triggers) if 'triggers' in item }}

          {{ item.description if 'description' in item }}

          ```
          {{ item.key }}
          ```

          Settings:
          | Item Setting | Value |
          | ------------ | ----- |
          {% if 'type' in item %}
          | Type | {{ item.type }} |
          {% endif %}
          {% if 'value_type' in item %}
          | Value type | {{ item.value_type }}{{ " in "+item.units if 'units' in item }} |
          {% endif %}
          {% if 'history' in item and item.history != '0' %}
          | History | {{ item.history }} |
          {% endif %}
          {% if 'trends' in item and item.trends != '0' %}
          | Trends | {{ item.trends }} |
          {% endif %}
          {% if 'type' in item and item.type == 'DEPENDENT' %}
          | Source item | `{{ item.master_item.key }}` |

          Preprocessing steps:
          | Type | Parameters |
          | ---- | ---------- |
          {% for prep in item.preprocessing %}
          | {{ prep.type }} | `{{ prep.parameters | to_json }}` |
          {% endfor %}
          {% endif %}
          {% endfor %}
          {% endif %}
          {% if triggers %}

          ## Triggers
          {% for trigger in ( triggers | flatten ) %}

          ## Trigger: {{ trigger.name }}

          {% for tag in trigger.tags %}![{{ tag.tag }}: {{ tag.value }}](https://img.shields.io/badge/{{ tag.tag }}-{{ tag.value }}-00c9bf){% endfor %}


          {{ trigger.description if 'description' in trigger }}
          Settings:
          | Trigger Setting | Values |
          | --------------- | ------ |
          | Priority | {{ trigger.priority }} |
          {% if 'manual_close' in trigger %}
          | Manual close | {{ trigger.manual_close }} |
          {% endif %}

          ```
          {{ trigger.expression }}
          ```
          {% endfor %}
          {% endif %}
          {% if 'graphs' in tpl %}

          ## Graphs

          The following graphs are included in this template.
          {% for graph in tpl.graphs %}
          * {{ graph.name }}
          {% endfor %}
          {% endif %}
          {% if 'dashboards' in tpl %}

          ## Dashboards

          The following Zabbix dashboards are included in this template.
          {% for dashboard in tpl.dashboards %}
          * {{ dashboard.name }}
          {% endfor %}
          {% endif %}
          {% if 'discovery_rules' in tpl %}

          # Discovery Rules
          {% for rule in tpl.discovery_rules %}
          {% set disco_triggers = [] %}

          ## Discovery Rule: {{ rule.name }}

          {{ rule.description }}
          ```
          {{ rule.key }}
          ```
          Settings:
          | Item Setting | Value |
          | ------------ | ----- |
          {% if 'type' in rule %}
          | Type | {{ rule.type }} |
          {% endif %}
          {% if 'value_type' in rule %}
          | Value type | {{ rule.value_type }}{{ " in "+rule.units if 'units' in rule }} |
          {% endif %}
          {% if 'history' in rule and rule.history != '0' %}
          | History | {{ rule.history }} |
          {% endif %}
          {% if 'trends' in rule and rule.trends != '0' %}
          | Trends | {{ rule.trends }} |
          {% endif %}
          {% if 'type' in rule and rule.type == 'DEPENDENT' %}
          | Source item | `{{ rule.master_item.key }}` |

          Preprocessing steps:
          | Type | Parameters |
          | ---- | ---------- |
          {% for prep in rule.preprocessing %}
          | {{ prep.type }} | `{{ prep.parameters | to_json }}` |
          {% endfor %}
          {% endif %}
          {% if 'item_prototypes' in rule %}

          ### Discovery Rule: {{ rule.name }}: Item Prototypes
          {% for item in rule.item_prototypes %}

          #### Discovery Rule: {{ rule.name }}: Item Prototype: {{ item.name }}

          {% for tag in item.tags %}![{{ tag.tag }}: {{ tag.value }}](https://img.shields.io/badge/{{ tag.tag }}-{{ tag.value }}-00c9bf){% endfor %}
          {{ disco_triggers.append(item.trigger_prototypes) if 'trigger_prototypes' in item }}

          {{ item.description if 'description' in item }}

          ```
          {{ item.key }}
          ```

          Settings:
          | Item Setting | Value |
          | ------------ | ----- |
          {% if 'type' in item %}
          | Type | {{ item.type }} |
          {% endif %}
          {% if 'value_type' in item %}
          | Value type | {{ item.value_type }}{{ " in "+item.units if 'units' in item }} |
          {% endif %}
          {% if 'history' in item and item.history != '0' %}
          | History | {{ item.history }} |
          {% endif %}
          {% if 'trends' in item and item.trends != '0' %}
          | Trends | {{ item.trends }} |
          {% endif %}
          {% if 'type' in item and item.type == 'DEPENDENT' %}
          | Source item | `{{ item.master_item.key }}` |

          Preprocessing steps:
          | Type | Parameters |
          | ---- | ---------- |
          {% for prep in item.preprocessing %}
          | {{ prep.type }} | `{{ prep.parameters | to_json }}` |
          {% endfor %}
          {% endif %}
          {% endfor %}
          {% endif %}
          {% if disco_triggers %}

          ### Discovery Rule: {{ rule.name }}: Discovery Triggers
          {% for trigger in ( disco_triggers | flatten ) %}

          #### Discovery Rule: {{ rule.name }}: Trigger Prototype: {{ trigger.name }}

          {% for tag in trigger.tags %}![{{ tag.tag }}: {{ tag.value }}](https://img.shields.io/badge/{{ tag.tag }}-{{ tag.value }}-00c9bf){% endfor %}


          {{ trigger.description if 'description' in trigger }}
          Settings:
          | Trigger Setting | Values |
          | --------------- | ------ |
          | Priority | {{ trigger.priority }} |
          {% if 'manual_close' in trigger %}
          | Manual close | {{ trigger.manual_close }} |
          {% endif %}

          ```
          {{ trigger.expression }}
          ```
          {% endfor %}
          {% endif %}
          {% if 'graph_prototypes' in rule %}

          ### Discovery Rule: {{ rule.name }}: Graph Prototypes

          The following graph prototypes are defined by this Template
          {% for graph in rule.graph_prototypes %}
          * {{ graph.name }}
          {% endfor %}
          {% endif %}
          {% endfor %}
          {% endif %}
          {% if 'vendor' in tpl and tpl.vendor.name == 'RaBe' %}

          ## License

          This template is free software: you can redistribute it and/or modify it under
          the terms of the GNU Affero General Public License as published by the Free
          Software Foundation, version 3 of the License.

          ## Copyright

          Copyright (c) 2017 - {{ ansible_date_time.year }} [Radio Bern RaBe](http://www.rabe.ch)
          {% endif %}
      loop: "{{ yaml.files | map(attribute='path') }}"
